name = "TightBinding"
uuid = "db00978d-8b5b-52b5-bbe7-ff451c144724"
authors = ["Yuki Nagai <cometscome@gmail.com>"]
version = "0.1.2"

[deps]
Dierckx = "39dd38d3-220a-591b-8e3c-4c3a8c710a94"
GR = "28b8d3ca-fb5f-59d9-8090-bfdbd6d07a71"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
