name = "TightBinding"
uuid = "4482633c-c459-11e8-019e-737cadda7745"
authors = ["Yuki Nagai <cometscome@gmail.com>"]
version = "0.1.1"

[deps]
GR = "28b8d3ca-fb5f-59d9-8090-bfdbd6d07a71"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
